apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: runner-config
spec:
  selector:
    matchLabels:
      name: runner-config
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-storage
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem

