- hosts: all
  become: yes
  tasks:
   - name: install nfs-common
     apt:
       name: nfs-common
       state: present

   - name: install rpcbind
     apt:
       name: rpcbind
       state: present

   - name: ensure nfs-service is enabled and running
     service:
       name: rpcbind
       enabled: true
       state: started

   - name: create nfs mount point
     shell:
       cmd: if [ -d /nfs-share ]; then echo folder exists; else  mkdir /nfs-share; fi

   - name: make an entry in /etc/fstab
     shell:
       cmd: if grep -q nfs-share /etc/fstab;then echo entry exist;else echo "192.168.100.13:/nfs-share /nfs-share nfs auto,nofail,noatime,nolock,intr,tcp 0 0">>/etc/fstab;fi

   - name: mount nfs share
     shell:
       warn: no
       cmd: mount -a
