apiVersion: v1
kind: ServiceAccount
metadata:
  name: nfs-svc-acc
  namespace: default

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nfs-provisioner-runner
  namespace: default
rules:
  - apiGroups:
      - ""
    resources:
      - persistentvolumes 
    verbs:
      - list
      - watch
      - get
      - create
      - delete
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
    verbs:
      - get
      - list
      - watch
      - update
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - update
      - create
      - patch
  - apiGroups:
      - "storage.k8s.io"
    resources:
      - storageclasses
    verbs:
      - list
      - watch
      - get

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: leader-nfs-provisioner
  namespace: default
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints 
    verbs:
      - get
      - list
      - watch
      - update
      - create
      - patch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: leader-nfs-provisioner-locking
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: leader-nfs-provisioner
subjects:
  - kind: ServiceAccount
    name: nfs-svc-acc
    namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: run-nfs-provisioner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  name: nfs-provisioner-runner
  kind: ClusterRole
subjects:
  - kind: ServiceAccount
    name: nfs-svc-acc
    namespace: default


